XSözlük/XSözlük.WEBUI/ViewComponents/AddEntryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using XSözlük.Business.Services;
using XSözlük.WEBUI.Models;

namespace XSözlük.WEBUI.ViewComponents
{
    public class AddEntryViewComponent :ViewComponent
    {
        private readonly IEntryService _entryService;
        public AddEntryViewComponent(IEntryService entryService)
        {
            _entryService = entryService;
        }
        public IViewComponentResult Invoke(int titleId,int userId)
        {
            var viewModel = new EntryAddViewModel
            {
                TitleId = titleId,
                UserId = userId,
                Entry = null

            };
            return View(viewModel);
        }
    }
}

XSözlük/XSözlük.WEBUI/Views/Shared/Components/Entries/Default.cshtml
@model List<HomeListViewModel>
@using XSözlük.WEBUI.Extensions




@for (int i = 0; i < 1; i++)
{
    var x = 0;
    var y = 0;

    @foreach (var item in Model)
    {
        @if (item.Sayi == 0)
        {



            <div class="fw-bold" style="color:darkorange; ">
                <h2 style="font-size:400%">@item.Title</h2>
            </div>

            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p class="fw-bold" style="font-size:200%">@item.Entry</p>

                    <footer class="blockquote-footer">@item.CreatedDate </footer>
                </blockquote>
            </div>


        }
        else
        {
            if (x == 0)
            {
                <div class="fw-bold" style="color:darkorange; ">
                    <h2 style="font-size:400%">@item.Title</h2>
                </div>

            }
            <div class="row">
                <div class="col-md-8">
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p class="fw-bold" style="font-size:200%">@item.Entry</p>

                            <footer class="blockquote-footer">@item.CreatedDate </footer>
                        </blockquote>
                    </div>
                </div>
                <div class="col-md-4" style="float:right">


                    @if (User.IsAdmin() || User.IsLogged())
                    {
                        @if (item.Entry.StartsWith("Uyulacak"))
                        {

                        }
                        else
                        {
                            @if (User.IsAdmin())
                            {
                                <a asp-controller="Home" asp-action="Delete" asp-route-entryId="@item.EntryId" style="color:darkred">Sil</a>
                            }
                            else if (item.UserId == User.GetUserId())
                            {
                                <a asp-controller="Home" asp-action="Delete" asp-route-entryId="@item.EntryId" style="color:darkred">Sil</a>
                            }
                            else
                            {
                                
                            }
                            
                        }
                    }



                </div>


            </div>


            if ((y == Model.Count - 1 || Model.Count == 0) && User.IsLogged())
            {
                <div>
                    <vc:add-entry title-id="@item.TitleId" user-id="@User.GetUserId()"></vc:add-entry>
                </div>
            }

            x++;
            y++;
        }

    }
}
