XSözlük/XSözlük.WEBUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using XSözlük.Business.Dtos;
using XSözlük.Business.Services;
using XSözlük.WEBUI.Areas.Admin.Models;

namespace XSözlük.WEBUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly ITitleService _titleService;
        private readonly IEntryService _entryService;
        public DashboardController(ITitleService titleService, IEntryService entryService)
        {
            _titleService = titleService;
            _entryService = entryService;
        }
        public IActionResult List()
        {
            var titleList = _titleService.GetTitles();
            var viewModel = titleList.Select(x => new ListTitleViewModel
            {
                Id = x.Id,
                Title = x.Title,
                CreatedDate = x.CreatedDate,
                ModifiedDate = x.ModifiedDate,

            }).ToList();

            return View("ListTitle", viewModel);
        }
        [HttpGet]
        public IActionResult AddTitle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddTitle(AddTitleViewModel formData)
        {
            var addTitleDto = new AddTitleDto
            {
                Id = formData.Id,
                Title = formData.Title,
            };

            var response = _titleService.AddTitle(addTitleDto);

            if (!response.IsSucceed)
            {
                ViewBag.ErrorMessage = response.ErrorMessage;
                return View(formData);
            }

            var viewModel = _titleService.GetTitles();

            var x = viewModel[viewModel.Count - 1].Id;  //en son eklenen başlığın idsini çektim

            _entryService.AddEntry(x);
            

            return RedirectToAction("List");

        }
        [HttpGet]
        public IActionResult EditTitle(int id)
        {
            var titleDto = _titleService.GetTitleById(id);

            var viewModel = new TitleViewModel
            {
                Title = titleDto.Title,
                Id = titleDto.Id
            };
            return View(viewModel);

        }
        [HttpPost]
        public IActionResult EditTitle(TitleViewModel formData)
        {
            var editTitleDto = new EditTitleDto
            {
                Id = formData.Id,
                Title = formData.Title,
            };
            _titleService.EditTitle(editTitleDto);

            return RedirectToAction("List");

        }
        public IActionResult DeleteTitle(int id)
        {
            _titleService.DeleteTitle(id);

            return RedirectToAction("List");
        }
    }
}

XSözlük/XSözlük.WEBUI/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using XSözlük.Business.Dtos;
using XSözlük.Business.Services;
using XSözlük.WEBUI.Models;

namespace XSözlük.WEBUI.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;
        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        [Route("kayit-ol")]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [Route("kayit-ol")]
        public IActionResult Register(RegisterViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View(formData);
            }
            var addUserDto = new AddUserDto
            {
                FirstName = formData.FirstName,
                LastName = formData.LastName,
                Email = formData.Email,
                Password = formData.Password,
            };
            var response = _userService.AddUser(addUserDto);

            if (!response.IsSucceed)
            {
                ViewBag.ErrorMessage = response.ErrorMessage;
                return View(formData);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LoginAsync(LoginViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }

            var loginDto = new LoginDto
            {
                Email = formData.Email,
                Password = formData.Password,
            };
           var userDto = _userService.Login(loginDto);

            if (userDto is null)
            {
                TempData["ErrorMessage"] = "Kullanıcı adı veya şifre hatalı.";

                return RedirectToAction("Index", "Home");
            }
            var claims = new List<Claim>();

            claims.Add(new Claim("id", userDto.Id.ToString()));
            claims.Add(new Claim("email", userDto.Email));
            claims.Add(new Claim("firstName", userDto.FirstName));
            claims.Add(new Claim("lastName", userDto.LastName));
            claims.Add(new Claim("userType", userDto.UserType.ToString()));

            claims.Add(new Claim(ClaimTypes.Role, userDto.UserType.ToString()));

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var autProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = new DateTimeOffset(DateTime.Now.AddHours(48))
            };
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity), autProperties);

            TempData["LoginMessage"] = "Giriş başarıyla yapıldı.";

            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }

    }
}

XSözlük/XSözlük.WEBUI/Views/Shared/_Layout.cshtml
@using XSözlük.WEBUI.Extensions
<html>

<head>
    <title>X Sözlük</title>

    <meta name="description" content="X Sözlük">
    <meta name="keywords" content="Bilgi, Öğrenme">
    <meta name="author" content="Oğuzhan Erdoğan">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        label.required:after {
            content: "*\00a0";
            color: red;
            margin-left: 2px;
        }
    </style>
</head>

<body class="d-flex flex-column min-vh-100">

    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    X Sözlük
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="#" class="nav-link px-2 text-secondary">Anasayfa</a></li>

                </ul>



                <div class="text-end">

                    @if (!User.IsLogged())
                    {

                        <a type="button" id="Giris" asp-controller="Auth" asp-action="Login" class=" btn btn-outline-light me-2">Giriş Yap</a>
                        <a type="button" id="Kayit" asp-controller="Auth" asp-action="Register" class=" btn btn-warning">Kayıt Ol</a>

                    }
                    else
                    {
                        var firstName = User.GetUserFirstName();
                        var lastName = User.GetUserLastName();

                        <div class="mt-2 row">
                            <div class="col-md-4" style="float:right">
                                @firstName @lastName
                            </div>


                            <div class="col-md-4 mt-2" style="float:right">
                                @if (User.IsAdmin())
                                {

                                    <div class="ms-3">
                                        <a asp-area="admin" asp-controller="Dashboard" asp-action="List" class="btn btn-primary">Admin</a>
                                    </div>

                                }
                            </div>
                            <div class="col-md-2 mt-2" style="text-align:center">
                                <a type="button" id="Cikis" asp-controller="Auth" asp-action="Logout" class=" btn btn-warning">Çıkış</a>

                            </div>
                        </div>
                    }




                </div>


            </div>
        </div>


    </header>

    <div class="container">

        @RenderBody()

    </div>

    <footer class="bg-dark text-white text-center mt-auto py-5 fw-bold">
        X SÖZLÜK
        <p class="text-secondary"> © Tüm Hakları Saklıdır. </p>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>

        @if (!string.IsNullOrWhiteSpace(TempData["ErrorMessage"]?.ToString()))
        {
            @:toastr.error("@TempData["ErrorMessage"]?.ToString()");
        }

        @if (!string.IsNullOrWhiteSpace(TempData["LoginMessage"]?.ToString()))
        {
            @:toastr.info("@TempData["LoginMessage"]?.ToString()");
        }
        @if (User.IsLogged())
        {
            @:$('#Giris').addClass('d-none');
            @:$('#Kayit').addClass('d-none');

        }



    </script>


</body>



</html>